services:
  product-mongo:
    image: mongo:7
    container_name: product-mongo
    ports:
      - "27017:27017"
    volumes:
      - product-mongo-data:/data/db

  shopping-mongo:
    image: mongo:7
    container_name: shopping-mongo
    ports:
      - "27018:27017"
    volumes:
      - shopping-mongo-data:/data/db

volumes:
  product-mongo-data:
  shopping-mongo-data:
